if(NOT EXISTS "${APP}" OR NOT EXISTS "${INPUT}")
    message(FATAL_ERROR "APP and INPUT must exist")
endif()
file(REMOVE "${OUTPUT}")
execute_process(COMMAND "${APP}" --smoke-test "${INPUT}" "${OUTPUT}"
    RESULT_VARIABLE result TIMEOUT 180
    OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr)
if(NOT result STREQUAL "0" OR NOT EXISTS "${OUTPUT}")
    message(FATAL_ERROR "Desktop import / retopology / export failed: ${result}\n${stdout}\n${stderr}")
endif()
file(STRINGS "${OUTPUT}" faces REGEX "^f ")
list(LENGTH faces face_count)
if(face_count LESS 1)
    message(FATAL_ERROR "Desktop exported no faces")
endif()
foreach(face IN LISTS faces)
    string(REGEX MATCHALL "[^ \t]+" tokens "${face}")
    list(LENGTH tokens count)
    if(NOT count EQUAL 5)
        message(FATAL_ERROR "Desktop output contains a non-quad face")
    endif()
endforeach()
