if(NOT DEFINED RETOPRIME_SOURCE_DIR OR NOT DEFINED TEST_ROOT OR NOT DEFINED OUTPUT_LAYOUT)
    message(FATAL_ERROR "RETOPRIME_SOURCE_DIR, TEST_ROOT, and OUTPUT_LAYOUT are required")
endif()

file(REMOVE_RECURSE "${TEST_ROOT}")
set(QUADRIFLOW_BINARY_DIR "${TEST_ROOT}/build")
set(STAGED_HELPER "${TEST_ROOT}/stage/retoprime-quads${EXECUTABLE_SUFFIX}")
if(OUTPUT_LAYOUT STREQUAL "Release")
    set(source_directory "${QUADRIFLOW_BINARY_DIR}/Release")
else()
    set(source_directory "${QUADRIFLOW_BINARY_DIR}")
endif()
file(MAKE_DIRECTORY "${source_directory}")
file(WRITE "${source_directory}/quadriflow${EXECUTABLE_SUFFIX}" "pinned-helper")

include("${RETOPRIME_SOURCE_DIR}/cmake/StageQuadriFlow.cmake")
file(READ "${STAGED_HELPER}" staged_contents)
if(NOT staged_contents STREQUAL "pinned-helper")
    message(FATAL_ERROR "The staged helper did not match the selected ${OUTPUT_LAYOUT} binary")
endif()
